alias cls='printf "\033c"'
alias youtube-dl='yt-dlp'
alias ytdl='yt-dlp'
alias lls='ls -GAhlg'
alias ffmpeg='ffmpeg -hide_banner'
alias locate='locate -ir'
alias vi='emacsclient -c -a emacs'
alias feh='feh -. -g 1600x900 -S mtime --start-at'